#!/bin/bash
set -e

# --------------------------------------
# ACCOUNTS MICROSERVICE
# --------------------------------------
psql -v ON_ERROR_STOP=1 --username "${DATABASE_ADMIN_USER}" --dbname "${DATABASE_NAME}" <<-EOF

-- Create schema if it does not exist
CREATE SCHEMA IF NOT EXISTS "${ACCOUNTS_DATABASE_SCHEMA}";

-- Create user if it does not exist
DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles WHERE rolname = '${ACCOUNTS_DATABASE_USER}'
    ) THEN
        CREATE USER "${ACCOUNTS_DATABASE_USER}" WITH PASSWORD '${ACCOUNTS_DATABASE_PASSWORD}';
    END IF;
END;
\$\$;

-- Make user the owner of the schema
ALTER SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" OWNER TO "${ACCOUNTS_DATABASE_USER}";

-- Grant full privileges on the schema
GRANT ALL PRIVILEGES ON SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" TO "${ACCOUNTS_DATABASE_USER}";

-- Grant privileges on all existing tables, sequences, and functions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" TO "${ACCOUNTS_DATABASE_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" TO "${ACCOUNTS_DATABASE_USER}";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" TO "${ACCOUNTS_DATABASE_USER}";

-- Ensure future objects created in the schema are accessible
ALTER DEFAULT PRIVILEGES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" GRANT ALL PRIVILEGES ON TABLES TO "${ACCOUNTS_DATABASE_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" GRANT ALL PRIVILEGES ON SEQUENCES TO "${ACCOUNTS_DATABASE_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" GRANT ALL PRIVILEGES ON FUNCTIONS TO "${ACCOUNTS_DATABASE_USER}";

EOF

# --------------------------------------
# TASKS MICROSERVICE
# --------------------------------------
psql -v ON_ERROR_STOP=1 --username "${DATABASE_ADMIN_USER}" --dbname "${DATABASE_NAME}" <<-EOF

-- Create schema if it does not exist
CREATE SCHEMA IF NOT EXISTS "${TASKS_DATABASE_SCHEMA}";

-- Create user if it does not exist
DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles WHERE rolname = '${TASKS_DATABASE_USER}'
    ) THEN
        CREATE USER "${TASKS_DATABASE_USER}" WITH PASSWORD '${TASKS_DATABASE_PASSWORD}';
    END IF;
END;
\$\$;

-- Make user the owner of the schema
ALTER SCHEMA "${TASKS_DATABASE_SCHEMA}" OWNER TO "${TASKS_DATABASE_USER}";

-- Grant full privileges on the schema
GRANT ALL PRIVILEGES ON SCHEMA "${TASKS_DATABASE_SCHEMA}" TO "${TASKS_DATABASE_USER}";

-- Grant privileges on all existing tables, sequences, and functions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "${TASKS_DATABASE_SCHEMA}" TO "${TASKS_DATABASE_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "${TASKS_DATABASE_SCHEMA}" TO "${TASKS_DATABASE_USER}";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "${TASKS_DATABASE_SCHEMA}" TO "${TASKS_DATABASE_USER}";

-- Ensure future objects created in the schema are accessible
ALTER DEFAULT PRIVILEGES IN SCHEMA "${TASKS_DATABASE_SCHEMA}" GRANT ALL PRIVILEGES ON TABLES TO "${TASKS_DATABASE_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA "${TASKS_DATABASE_SCHEMA}" GRANT ALL PRIVILEGES ON SEQUENCES TO "${TASKS_DATABASE_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA "${TASKS_DATABASE_SCHEMA}" GRANT ALL PRIVILEGES ON FUNCTIONS TO "${TASKS_DATABASE_USER}";

EOF