#!/bin/bash
set -e

# --------------------------------------
# ACCOUNTS MICROSERVICE
# --------------------------------------
psql -v ON_ERROR_STOP=1 --username "${DATABASE_ADMIN_USER}" --dbname "${DATABASE_NAME}" <<-EOF

CREATE SCHEMA IF NOT EXISTS "${ACCOUNTS_DATABASE_SCHEMA}";

DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles WHERE rolname = '${ACCOUNTS_DATABASE_USER}'
    ) THEN
        CREATE USER "${ACCOUNTS_DATABASE_USER}" WITH PASSWORD '${ACCOUNTS_DATABASE_PASSWORD}';
    END IF;
END;
\$\$;

GRANT USAGE, CREATE ON SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}" TO "${ACCOUNTS_DATABASE_USER}";

ALTER DEFAULT PRIVILEGES FOR USER ${DATABASE_ADMIN_USER}
IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${ACCOUNTS_DATABASE_USER}";

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA "${ACCOUNTS_DATABASE_SCHEMA}"
TO "${ACCOUNTS_DATABASE_USER}";

EOF

# --------------------------------------
# TASKS MICROSERVICE
# --------------------------------------
psql -v ON_ERROR_STOP=1 --username "${DATABASE_ADMIN_USER}" --dbname "${DATABASE_NAME}" <<-EOF

CREATE SCHEMA IF NOT EXISTS "${TASKS_DATABASE_SCHEMA}";

DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles WHERE rolname = '${TASKS_DATABASE_USER}'
    ) THEN
        CREATE USER "${TASKS_DATABASE_USER}" WITH PASSWORD '${TASKS_DATABASE_PASSWORD}';
    END IF;
END;
\$\$;

GRANT USAGE, CREATE ON SCHEMA "${TASKS_DATABASE_SCHEMA}" TO "${TASKS_DATABASE_USER}";

ALTER DEFAULT PRIVILEGES FOR USER ${DATABASE_ADMIN_USER}
IN SCHEMA "${TASKS_DATABASE_SCHEMA}"
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${TASKS_DATABASE_USER}";

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA "${TASKS_DATABASE_SCHEMA}"
TO "${TASKS_DATABASE_USER}";

EOF